version: 2.1
orbs:
  todays-imas-idol-command: yutagoto/todays-imas-idol@dev:first

jobs:
  build:
    docker:
    - image: ubuntu:18.04
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y sudo
      - todays-imas-idol-command/echo-todays-imas-idol

workflows:
  main:
    jobs:
    - build