version: 2.1
ubuntu_image: &ubuntu_image
  ubuntu:18.04
install-sudo: &install-sudo |
  apt-get update
  apt-get install -y sudo

orbs:
  todays-imas-idol: yutagoto/todays-imas-idol@volatile

executors:
  ubuntu-docker:
    docker:
      - image: *ubuntu_image
        environment:
          TZ: Asia/Tokyo

jobs:
  echo:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/echo-todays-imas-idol

  slack:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/slack-notification-todays-imas-idol:
          slack_username: CiecleCI
          slack_icon: ":ciecleci:"
  discord:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/discord-notification-todays-imas-idol:
          discord_username: CiecleCI
  line:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/line-notification-todays-imas-idol

workflows:
  main:
    jobs:
    - echo
    - slack:
        requires:
          - echo
    - discord:
        requires:
          - echo
    - line:
        requires:
          - echo

  smoke_test:
    triggers:
      - schedule:
          cron: "0 12 * * 0"
          filters:
            branches:
              only: master
    jobs:
    - echo

  smoke_test_slack:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
    - slack

  smoke_test_discord:
    triggers:
      - schedule:
          cron: "0 3 * * 0"
          filters:
            branches:
              only: master
    jobs:
    - discord

  smoke_test_line:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only: master
    jobs:
    - line
