version: 2.1
ubuntu_image: &ubuntu_image
  ubuntu:18.04
install-sudo: &install-sudo |
  apt-get update
  apt-get install -y sudo

orbs:
  todays-imas-idol: yutagoto/todays-imas-idol@dev:first

executors:
  ubuntu-docker:
    docker:
      - image: *ubuntu_image
        environment:
          TZ: Asia/Tokyo

jobs:
  build:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/echo-todays-imas-idol

  slack:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/slack-notification-todays-imas-idol:
          slack_username: CiecleCI
          slack_icon: ":ciecleci:"

  discord:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/discord-notification-todays-imas-idol:
          discord_username: CiecleCI
  chatwork:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - todays-imas-idol/chatwork-notification-todays-imas-idol

workflows:
  main:
    jobs:
    - build
    - slack
    - discord
    - chatwork

  smoke_test:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only: master
    jobs:
    - build

  smoke_test_slack:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
    - slack

  smoke_test_discord:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master
    jobs:
    - discord

  smoke_test_chatwork:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
    - chatwork
