version: 2.1
orbs:
  todays-imas-idol: yutagoto/todays-imas-idol@dev:first

jobs:
  build:
    docker:
    - image: ubuntu:18.04
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y sudo
      - todays-imas-idol/echo-todays-imas-idol
  slack:
    docker:
    - image: ubuntu:18.04
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y sudo
      - todays-imas-idol/slack-notification-todays-imas-idol

workflows:
  main:
    jobs:
    - build
    - slack

  smoke_test:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only: master
    jobs:
    - build

  smoke_test_slack:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
    - build
